import { useSnapshot } from "../api";
import { ArtifactGrid } from "../components/artifacts/ArtifactGrid";
import { PageHeader } from "../components/layout/PageHeader";
import { SectionCard } from "../components/common/SectionCard";
import type { ArtifactEntry } from "../types";

const GROUPS: { key: ArtifactEntry["sourceScreen"]; title: string }[] = [
  { key: "self-healing", title: "Self-healing" },
  { key: "visual-diff", title: "Visual regression" },
  { key: "reports", title: "Test reporter" },
];

export function ArtifactsPage() {
  const { artifacts } = useSnapshot();

  return (
    <div>
      <PageHeader title="Artifacts" description={`${artifacts.length} files generated by the three components' real example runs.`} />

      <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
        {GROUPS.map((group) => {
          const items = artifacts.filter((a) => a.sourceScreen === group.key);
          if (items.length === 0) return null;
          return (
            <SectionCard key={group.key} title={`${group.title} (${items.length})`}>
              <ArtifactGrid artifacts={items} />
            </SectionCard>
          );
        })}
      </div>
    </div>
  );
}
